DEPLOY-656: Remove nginx server header
Alfresco/alfresco-infrastructure-deployment pull request #41
Opened 2019-02-06 21:43 UTC by svidrascu

2019-02-06 21:57 UTC, rgauss requested changes

2019-02-06 21:57 UTC, rgauss commented on helm/alfresco-infrastructure/values.yaml
> -activemq:
Is this intentional?

2019-02-06 21:57 UTC, rgauss commented on helm/alfresco-infrastructure/values.yaml
> -alfresco-identity-service:
Is this intentional?

2019-02-07 06:24 UTC, svidrascu commented on helm/alfresco-infrastructure/values.yaml
> -activemq:
yes, because they don't do anything.

2019-02-07 06:24 UTC, svidrascu commented on helm/alfresco-infrastructure/values.yaml
> -alfresco-identity-service:
This also has no effect on anything.

2019-02-07 07:20 UTC, cristina-sirbu commented
I understand that removing  activemq.enabled and alfresco-identity-service.enabled doesn't have any impact but I think it's worth keeping them because people that want to customize the Infrastructure chart might look just at the values file. Not everyone is looking in every single file of the chart or documentation. Just my opinion.

2019-02-07 11:21 UTC, rgauss commented
> I understand that removing activemq.enabled and alfresco-identity-service.enabled doesn't have any impact but I think it's worth keeping them because people that want to customize the Infrastructure chart might look just at the values file. Not everyone is looking in every single file of the chart or documentation. Just my opinion.

Agreed.

2019-02-07 12:05 UTC, kconkas commented
Just my 5c: I find the inclusion of `activemq.enabled` and `alfresco-identity-service.enabled` in `values.yaml` rather misleading. Take a look at AUTH-251 for a recent example of confusion it can cause. 

If the user expects that, say, `activemq.enabled` in `values.yaml` controls whether activemq is enabled, then they will also expect when `alfresco-infrastructure` is deployed as a dependency of a parent chart this value can be overriden through the master chart. For example, when pulled as part of `alfresco-dbp` chart, the user could reasonably assume that in that case to disable activemq they would need to override `alfresco-infrastructure.activemq.enabled` (because this is a child chart) when in reality this will make no effect on the condition in `requirements.yaml`. 

To me, this confusion is a bigger issue than users not going through documentation.

2019-02-07 12:28 UTC, rgauss commented
> the user could reasonably assume that in that case to disable activemq they would need to override `alfresco-infrastructure.activemq.enabled` (because this is a child chart) when in reality this will make no effect on the condition in `requirements.yaml`.

Hmm, we seem to be inconsistent with our requirement conditions.  Should we remove the `alfresco-infrastructure` prefix from the requirement conditions in this chart?

2019-02-07 14:16 UTC, svidrascu commented
No we shouldnt remove it. 
This is our agreement from the start. 
We always add the parent of the chart in the condition otherwise if a parent chart like dbp comes on top of infra along with another chart having an extra active-mq then you would not be able to disable one of them. Just both since the conditions are global variables.

2019-02-08 11:05 UTC, rgauss commented
> If we still want this here as an easy way to disable the components ill just write them the right way.

I think that would be helpful for newcomers.

For others' reference: https://github.com/helm/helm/issues/2479

2019-02-08 16:06 UTC, rgauss approved these changes

2019-02-08 17:10 UTC, jottley approved these changes

2019-02-11 08:19 UTC, merged